sudo: false
language: ruby
rvm:
  - 2.4.2
  - 2.5.0
  - 2.5.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install: gem install bundler -v 1.16.1
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
